### ISSUE TITLE
[Bug]: Error on windows 11 when trying to copy assets

### ISSUE THREAD

**Issue by BearGryllsTV** [tomatophp/filament-form-builder#1]
### What happened?

I ran the command as per the documentation and I got the error be;pw

PS C:\Users\Gav\Desktop\SomersetYouth> php artisan vendor:publish --tag="filament-form-builder-views"

   INFO  Publishing [filament-form-builder-views] assets.

   ERROR  Can't locate path: <C:\Users\Gav\Desktop\SomersetYouth\vendor\tomatophp\filament-form-builder\src/../resources/views>.  

### How to reproduce the bug

php artisan vendor:publish --tag="filament-form-builder-views"

### Package Version

dev-master

### PHP Version

8.2.0

### Laravel Version

11.31

### Which operating systems does with happen with?

Windows

**Comment by fadymondy** [comment]
project still under development we don't release it yet
