### ISSUE TITLE
[Bug]: Installation bug

### ISSUE THREAD

**Issue by BearGryllsTV** [tomatophp/filament-form-builder#2]
### What happened?

When installing it could not find the routes/web.php I had to comment out this line to complete installation

 //Register Routes
 //$this->loadRoutesFrom(__DIR__ . '/../routes/web.php');

### How to reproduce the bug

php artisan filament-form-builder:install on windows

### Package Version

dev-master

### PHP Version

8.2.0

### Laravel Version

11.31

### Which operating systems does with happen with?

Windows

**Comment by fadymondy** [comment]
project still under development we don't release it yet
